### ISSUE TITLE
Support @Column(unique = true) for Cassandra

### ISSUE THREAD

**Issue by yhilem** [datanucleus/datanucleus-cassandra#34]
Hi,

I'm using JClouds with DataNucleus JPA for Cassandra (https://github.com/datanucleus/datanucleus-cassandra/issues/33) and all the tests fail because of this error:
```
testBlobExists
javax.persistence.NonUniqueResultException: Expected a single result for query: SELECT FROM org.jclouds.jdbc.entity.ContainerEntity c WHERE c.name = :name : The query returned more than one instance BUT either unique is set to true or only aggregates are to be returned, so should have returned one result maximum
org.datanucleus.store.query.QueryNotUniqueException: The query returned more than one instance BUT either unique is set to true or only aggregates are to be returned, so should have returned one result maximum
	at org.datanucleus.store.query.Query.executeQuery(Query.java:2001)
	at org.datanucleus.store.query.Query.executeWithMap(Query.java:1873)
	at org.datanucleus.api.jpa.JPAQuery.getSingleResult(JPAQuery.java:257)
	at org.jclouds.jdbc.repository.ContainerRepository.findContainerByName(ContainerRepository.java:40)
	at org.jclouds.jdbc.service.JdbcService.findContainerByName(JdbcService.java:86)
	at org.jclouds.jdbc.service.JdbcService$$EnhancerByGuice$$99921f29.CGLIB$findContainerByName$10(<generated>)
	at org.jclouds.jdbc.service.JdbcService$$EnhancerByGuice$$99921f29$$FastClassByGuice$$5a562b39.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
	at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:70)
	at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
	at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52)
	at org.jclouds.jdbc.service.JdbcService$$EnhancerByGuice$$99921f29.findContainerByName(<generated>)
	at org.jclouds.jdbc.strategy.JdbcStorageStrategy.containerExists(JdbcStorageStrategy.java:93)
	at org.jclouds.blobstore.config.LocalBlobStore.blobExists(LocalBlobStore.java:626)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37)
	at com.sun.proxy.$Proxy46.blobExists(Unknown Source)
	at org.jclouds.jdbc.BaseJdbcBlobStoreTest.testBlobExists(BaseJdbcBlobStoreTest.java:460)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at org.datanucleus.api.jpa.JPAQuery.getSingleResult(JPAQuery.java:266)
	at org.jclouds.jdbc.repository.ContainerRepository.findContainerByName(ContainerRepository.java:40)
	at org.jclouds.jdbc.service.JdbcService.findContainerByName(JdbcService.java:86)
	at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:70)
	at org.jclouds.jdbc.strategy.JdbcStorageStrategy.containerExists(JdbcStorageStrategy.java:93)
	at org.jclouds.blobstore.config.LocalBlobStore.blobExists(LocalBlobStore.java:626)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37)
	at com.sun.proxy.$Proxy46.blobExists(Unknown Source)
	at org.jclouds.jdbc.BaseJdbcBlobStoreTest.testBlobExists(BaseJdbcBlobStoreTest.java:460)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 28 stack frames
```
The cause is the non respect of the constraint defined for name attribute (https://github.com/jclouds/jclouds-labs/blob/master/jdbc/src/main/java/org/jclouds/jdbc/entity/ContainerEntity.java#L37):
```
@Entity
@Table
public class ContainerEntity {

   @Id
   @GeneratedValue
   private Long id;

   @Column(unique = true)
   private String name;

   private Date creationDate;

   private ContainerAccess containerAccess;
```
Thus, the following method generates the exception described above (https://github.com/jclouds/jclouds-labs/blob/master/jdbc/src/main/java/org/jclouds/jdbc/repository/ContainerRepository.java#L36):
```
   public ContainerEntity findContainerByName(String name) {
      try {
         return entityManager.get().createQuery("SELECT c FROM " + entityClass.getName() + " c WHERE c.name = :name", entityClass)
               .setParameter("name", name)
               .getSingleResult();
      } catch (NoResultException e) {
         return null;
      }
   }
```
![2019-03-17 10_58_43-cqlsh](https://user-images.githubusercontent.com/13407261/54488673-0445d580-48a5-11e9-859b-2069c390dcc9.png)

Thanks
Youcef HILEM

**Comment by andyjefferson** [comment]
No testcase demonstrating anything, so closing. Can be reopened if complying with basic rules of this project, or if contributing a PR for whatever this is
